[workspace]
git_release_name = "v{{ version }}"
git_tag_name = "v{{ version }}"
publish = false
release = false
git_release_enable = false
git_tag_enable = false

[[package]]
name = "gelx"
changelog_path = "crates/gelx/changelog.md"
publish = true
release = true
git_tag_enable = true
git_release_enable = true

[[package]]
name = "gelx_cli"
changelog_path = "crates/gelx_cli/changelog.md"
publish = true
release = true

[[package]]
name = "gelx_macros"
changelog_path = "crates/gelx_macros/changelog.md"
publish = true
release = true

[[package]]
name = "gelx_core"
changelog_path = "crates/gelx_core/changelog.md"
publish = true
release = true

[changelog]
commit_parsers = [
	{ message = "^feat", group = "<!-- 0 -->🎉 Added" },
	{ message = "^changed", group = "📝 Changed" },
	{ message = "^fix", group = "<!-- 1 -->🐛 Bug Fixes" },
	{ message = "^deprecated", group = "🗑️ Deprecated" },
	{ message = "^doc", group = "<!-- 3 -->📚 Documentation" },
	{ message = "^perf", group = "<!-- 4 -->⚡ Performance" },
	{ message = "^refactor\\(clippy\\)", skip = true },
	{ message = "^refactor", group = "<!-- 2 -->🚜 Refactor" },
	{ message = "^style", group = "<!-- 5 -->🎨 Styling" },
	{ message = "^test", group = "<!-- 6 -->🧪 Testing" },
	{ message = "^chore\\(release\\):", skip = true },
	{ message = "^chore: release", skip = true },
	{ message = "^chore\\(deps.*\\)", skip = true },
	{ message = "^chore\\(pr\\)", skip = true },
	{ message = "^chore\\(pull\\)", skip = true },
	{ message = "^chore\\(npm\\).*yarn\\.lock", skip = true },
	{ message = "^chore|^ci", group = "<!-- 7 -->⚙️ Miscellaneous Tasks" },
	{ body = ".*security", group = "<!-- 8 -->🛡️ Security" },
	{ message = "^revert", group = "<!-- 9 -->◀️ Revert" },
]
