[language-server.nil]
command = "nil"

[language-server.nil.config]
formatting = { command = "nixpkgs-fmt" }

[language-server.rust-analyzer.config.check]
command = "clippy"
features = "all"

[language-server.rust-analyzer.config.cargo]
features = "all"

[[language]]
name = "markdown"
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "dprint", args = ["fmt", "--stdin", "file.md"] }
auto-format = true

[[language]]
name = "rust"
language-servers = ["rust-analyzer"]
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "dprint", args = ["fmt", "--stdin", "file.rs"] }
auto-format = true

[[language]]
name = "yaml"
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "dprint", args = ["fmt", "--stdin", "file.yaml"] }
auto-format = true

[[language]]
name = "toml"
indent = { tab-width = 2, unit = "\t" }
language-servers = ["taplo"]
formatter = { command = "dprint", args = ["fmt", "--stdin", "Cargo.toml"] }
auto-format = true

[[language]]
name = "nix"
language-servers = ["nil"]
indent = { tab-width = 2, unit = "\t" }
formatter = { command = "dprint", args = ["fmt", "--stdin", "file.nix"] }
auto-format = true
