[alias]
# bins
llvm-cov = ["bin", "cargo-llvm-cov"]
nextest = ["bin", "cargo-nextest"]
insta = ["bin", "cargo-insta"]
leptos = ["bin", "cargo-leptos"]
mutants = ["bin", "cargo-mutants"]
test_codegen = ["nextest", "run", "-p", "edgedb_codegen"]
test_macros = ["nextest", "run", "-p", "edgedb_macros", "--features", "serde,query,builder"]
