[alias]
# bins
llvm-cov = ["bin", "cargo-llvm-cov"]
nextest = ["bin", "cargo-nextest"]
insta = ["bin", "cargo-insta"]
leptos = ["bin", "cargo-leptos"]
mutants = ["bin", "cargo-mutants"]
test_edgedb = ["nextest", "run", "-p", "edgedb_generator"]
