[alias]
# bins
deny = ["bin", "cargo-deny"]
insta = ["bin", "cargo-insta"]
llvm-cov = ["bin", "cargo-llvm-cov"]
nextest = ["bin", "cargo-nextest"]

# testing
test_all_features = ["nextest", "run", "--all-features"]
test_no_features = ["nextest", "run", "--package", "gelx"]
test_docs = ["test", "--doc", "--all-features"]
coverage_all_features = ["llvm-cov", "--no-report", "--all-features"]
coverage_no_features = ["llvm-cov", "--no-report", "--package", "gelx"]
coverage_docs = ["llvm-cov", "--no-report", "--doc", "--all-features"]
coverage_report = ["llvm-cov", "report", "--doctests", "--codecov", "--output-path", "codecov.json"]
