[alias]
# bins
build-all-features = ["bin", "cargo-build-all-features"]
check-all-features = ["bin", "cargo-check-all-features"]
test-all-features = ["bin", "cargo-test-all-features"]
deny = ["bin", "cargo-deny"]
insta = ["bin", "cargo-insta"]
llvm-cov = ["bin", "cargo-llvm-cov"]
nextest = ["bin", "cargo-nextest"]

# testing
test_all_features = ["nextest", "run", "--all-features"]
test_no_features = ["nextest", "run", "--package", "gelx"]
test_docs = ["test", "--doc", "--all-features"]
coverage_all_features = ["llvm-cov", "--no-report", "--all-features"]
coverage_no_features = ["llvm-cov", "--no-report", "--package", "gelx"]
coverage_docs = ["llvm-cov", "--no-report", "--doc", "--all-features"]
coverage_report = ["llvm-cov", "report", "--doctests", "--codecov", "--output-path", "codecov.json"]
coverage_html = ["llvm-cov", "report", "--doctests", "--output-dir", "coverage", "--html", "--open"]
