name: "ci"
permissions:
  pull-requests: write
  contents: write
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
env:
  EDGEDB_INSTANCE: "edgedb_codegen"
  EDGEDB_BRANCH: "main"
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}
jobs:
  lint:
    timeout-minutes: 15
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup
        uses: ./.github/actions/devenv
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          nix-cache: /tmp/nixcache
      - name: lint
        run: lint:all
        shell: bash
  test:
    timeout-minutes: 15
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup
        uses: ./.github/actions/devenv
      - name: test
        run: test:all
        shell: bash
  build:
    timeout-minutes: 15
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout repository
        uses: actions/checkout@v4
      - name: setup
        uses: ./.github/actions/devenv
      - name: build
        run: cargo build
        shell: bash
  release:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - name: setup Rust
        uses: dtolnay/rust-toolchain@stable
      - name: checkout
        uses: actions/checkout@v4
      - name: release
        uses: MarcoIeni/release-plz-action@v0.5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
